import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Fone Bluetooth Pro",
    description: "Cancelamento de ruído ativo, 40h bateria",
    benefit: "Som cristalino sem fios",
    image: "/wireless-bluetooth-headphones-black-premium.jpg",
    affiliateLink: "https://amazon.com.br/exemplo",
    category: "eletronicos",
    subcategory: "fones",
    originalPrice: 299.9,
    discountPrice: 149.9,
    stock: 12,
    isLimitedOffer: true,
    offerEndTime: new Date(Date.now() + 3600000 * 5).toISOString(),
    isFeatured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Smartwatch Fitness",
    description: "Monitor cardíaco, GPS, resistente à água",
    benefit: "Seu treino no pulso",
    image: "/smartwatch-fitness-tracker-black-modern.jpg",
    affiliateLink: "https://shopee.com.br/exemplo",
    category: "eletronicos",
    subcategory: "smartwatches",
    originalPrice: 450.0,
    discountPrice: 279.9,
    stock: 8,
    isLimitedOffer: true,
    offerEndTime: new Date(Date.now() + 3600000 * 2).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Curso Marketing Digital",
    description: "Do zero ao avançado em 30 dias",
    benefit: "Transforme sua carreira",
    image: "/digital-marketing-course-laptop-online-education.jpg",
    affiliateLink: "https://hotmart.com/exemplo",
    category: "digitais",
    subcategory: "cursos",
    originalPrice: 997.0,
    discountPrice: 297.0,
    isFeatured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Power Bank 20000mAh",
    description: "Carrega 5x seu celular",
    benefit: "Energia sempre com você",
    image: "/power-bank-portable-charger-black-sleek.jpg",
    affiliateLink: "https://amazon.com.br/exemplo2",
    category: "eletronicos",
    subcategory: "power-banks",
    originalPrice: 189.9,
    discountPrice: 89.9,
    stock: 25,
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Ring Light Pro",
    description: "Iluminação profissional para lives",
    benefit: "Brilhe nas redes sociais",
    image: "/ring-light-professional-photography-lighting.jpg",
    affiliateLink: "https://shopee.com.br/exemplo2",
    category: "casa",
    subcategory: "iluminacao",
    originalPrice: 299.9,
    discountPrice: 159.9,
    isLimitedOffer: true,
    offerEndTime: new Date(Date.now() + 3600000 * 8).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Ebook Renda Extra",
    description: "10 formas de ganhar dinheiro online",
    benefit: "Comece a lucrar hoje",
    image: "/ebook-money-online-business-digital-product.jpg",
    affiliateLink: "https://monetizze.com.br/exemplo",
    category: "digitais",
    subcategory: "ebooks",
    originalPrice: 97.0,
    discountPrice: 27.0,
    isFeatured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Cadeira Gamer RGB",
    description: "Ergonômica com apoio lombar",
    benefit: "Conforto total no jogo",
    image: "/gaming-chair-rgb-lights-black-ergonomic.jpg",
    affiliateLink: "https://amazon.com.br/exemplo3",
    category: "casa",
    subcategory: "decoracao",
    originalPrice: 1299.9,
    discountPrice: 799.9,
    stock: 5,
    isLimitedOffer: true,
    offerEndTime: new Date(Date.now() + 3600000 * 12).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Kindle Paperwhite",
    description: "Tela antirreflexo, luz ajustável",
    benefit: "Milhares de livros no bolso",
    image: "/kindle-e-reader-black-device-reading.jpg",
    affiliateLink: "https://amazon.com.br/exemplo4",
    category: "eletronicos",
    subcategory: "gadgets",
    originalPrice: 599.9,
    discountPrice: 449.9,
    createdAt: new Date().toISOString(),
  },
  {
    id: "9",
    name: "Camiseta Dry Fit",
    description: "Tecido respirável, secagem rápida",
    benefit: "Performance no treino",
    image: "/dry-fit-athletic-shirt-black.jpg",
    affiliateLink: "https://shopee.com.br/exemplo3",
    category: "moda",
    subcategory: "moda-fitness",
    originalPrice: 89.9,
    discountPrice: 49.9,
    stock: 50,
    createdAt: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Kit Skincare Completo",
    description: "Limpeza, hidratação e proteção",
    benefit: "Pele radiante em 7 dias",
    image: "/skincare-products-kit-bottles.jpg",
    affiliateLink: "https://amazon.com.br/exemplo5",
    category: "beleza",
    subcategory: "skincare",
    originalPrice: 249.9,
    discountPrice: 149.9,
    isFeatured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "11",
    name: "Halteres Ajustáveis",
    description: "De 2kg a 24kg em um só equipamento",
    benefit: "Academia em casa",
    image: "/adjustable-dumbbells-fitness-equipment.jpg",
    affiliateLink: "https://amazon.com.br/exemplo6",
    category: "esporte",
    subcategory: "equipamentos-treino",
    originalPrice: 899.9,
    discountPrice: 599.9,
    stock: 15,
    isLimitedOffer: true,
    offerEndTime: new Date(Date.now() + 3600000 * 24).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "12",
    name: "Mochila Antifurto",
    description: "USB integrado, compartimentos seguros",
    benefit: "Viaje com segurança",
    image: "/anti-theft-backpack-black-modern.jpg",
    affiliateLink: "https://shopee.com.br/exemplo4",
    category: "viagem",
    subcategory: "mochilas-viagem",
    originalPrice: 189.9,
    discountPrice: 99.9,
    createdAt: new Date().toISOString(),
  },
]
